services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart:
      always
    environment:
      POSTGRES_PASSWORD: toChangeInProductionWithEnvVariable
      POSTGRES_DB: onePercent